CREATE TABLE auth.users (
    instance_id UUID NULL,
    id UUID PRIMARY KEY,
    aud TEXT NOT NULL,
    role TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    email_confirmed_at TIMESTAMP WITH TIME ZONE,
    invited_at TIMESTAMP WITH TIME ZONE,
    phone TEXT NOT NULL,
    phone_confirmed_at TIMESTAMP WITH TIME ZONE,
    confirmation_sent_at TIMESTAMP WITH TIME ZONE,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    recovery_sent_at TIMESTAMP WITH TIME ZONE,
    new_email TEXT,
    email_change_sent_at TIMESTAMP WITH TIME ZONE,
    new_phone TEXT,
    phone_change_sent_at TIMESTAMP WITH TIME ZONE,
    reauthentication_sent_at TIMESTAMP WITH TIME ZONE,
    last_sign_in_at TIMESTAMP WITH TIME ZONE,
    app_metadata JSONB,
    user_metadata JSONB,
    factors JSONB,
    identities JSONB,
    encrypted_password VARCHAR(255) NOT NULL,
    email_change_token VARCHAR(255) NULL DEFAULT '',
    confirmation_token VARCHAR(255) NULL DEFAULT '',
    recovery_token VARCHAR(255) NULL DEFAULT '',
    email_change_token_current VARCHAR(255) NULL DEFAULT '',
    email_change_token_new VARCHAR(255) NULL DEFAULT '',
    phone_change_token VARCHAR(255) NULL DEFAULT '',
    reauthentication_token VARCHAR(255) NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    banned_until TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE
);
